import React from 'react';
import { Admin } from './Admin';
import { Text } from '@chakra-ui/react';

export const AdminAddProduct = () => {
  return (
    <div>
      <Admin>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
        <Text>AdminAddProduct</Text>
      </Admin>
    </div>
  )
}
